### ISSUE TITLE
models.py の to_dict()

### ISSUE THREAD

**Issue by tinaxd** [kanicreampasta/rakutanAPI-py#2]
'accepted' : self.accepted になってるけど、from_dict のときみたいに 'accept_prev', 'accept_prev2', 'accept_prev3' に分解しなくていいの？

**Comment by das08** [comment]
扱いやすさの観点からacceptedとtotalはRakutanオブジェクト内では3年分の数値を入れたlistにしよかなと。

ただmongodbでは_prev2, _prev3に数値入れてる(postgresql時代の名残)からfrom_dict()でlist に置き換えてる。

もっといい方法あれば教えてー

**Comment by tinaxd** [comment]
mongoのほうもリストにできない？

**Comment by das08** [comment]
csvでimportしてるから出来なさそう。

と思ったけど行けそうなこと書いてあったから今度試してみるわ。csvmerger改変要りそう
https://stackoverflow.com/questions/44622394/import-csv-data-as-array-in-mongodb-using-mongoimport

**Comment by das08** [comment]
field名はキャメルケース、単位取得に関する数値はArrayで管理するようにmongodbの構成を変更した。
(mongoimportはcsvにして後からバッチ回してArray化)
